### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by ghost** [monsterkodi/clippo#2]
This looks like a great little app, mind including some build instructions? (macOS)

**Comment by monsterkodi** [comment]
sure.

first, install my build tool **konrad**:

`npm install -g konrad`

run it in the project directory to generate the package.json:

`konrad`

then install the dependencies as usual:

`npm install`

last step to build the app:

`npm run build`

please let me know if you encounter any problems.

**Comment by monsterkodi** [comment]
I just fixed some issues on mac. Please clone the latest version before you try it.

Alternatively you could just download the prepackaged build from the releases page.
It is a bit older but should work as well.
