### ISSUE TITLE
Official latest release for mac?

### ISSUE THREAD

**Issue by krainboltgreene** [monsterkodi/clippo#3]
Seems like the latest release for macos is significantly out of date?

**Comment by monsterkodi** [comment]
Yes and no :-)

The app was developed for mac first. 
I have used the mac version you can download right now quite a while and it should work well.

When I had to move to windows, I refactored most of my tools to use the same basic app-skeleton.
As a side effect, the latest version of clippo for windows might have some small minor features added, but on the flip side, it looks like a windows app now (even on mac :-). 

I will upload a newer version for mac. In the meantime, you could try out the old one. You might like it even better.

**Comment by monsterkodi** [comment]
OK, I have uploaded the latest build for mac. 
You have the choice now :-)
Please let me know if something doesn't work.
